// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://worqpvpvgfjuvqexpofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvcnFwdnB2Z2ZqdXZxZXhwb2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDM5NzcsImV4cCI6MjA2NTM3OTk3N30.H64MPFh_h-d23KO2Mt7Ot7vjMxhZMzIVNjhvYeDfX8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);